import Link from 'next/link'
import type { Metadata } from 'next'
import Image from 'next/image'
import { DocsShell } from '@/components/docs-shell'
import { DocSection, DocSubheading, Callout, StepList, FieldTable } from '@/components/doc-blocks'

export const metadata: Metadata = {
  title: 'Commission Report (Mobile App) | InsureBook Documentation',
  description:
    'Commission Report documentation for the InsureBook mobile app.',
}

export default function MobileAppCommissionReportPage() {
  return (
    <DocsShell>
      {/* Breadcrumb */}
      <nav aria-label="Breadcrumb" className="text-sm text-muted-foreground">
        <ol className="flex items-center gap-1.5">
          <li>
            <Link href="/" className="hover:text-foreground">
              Docs
            </Link>
          </li>
          <li aria-hidden="true">/</li>
          <li>
            <Link href="/modules/mobile-app" className="hover:text-foreground">
              Mobile App
            </Link>
          </li>
          <li aria-hidden="true">/</li>
          <li>
            <span className="text-foreground">Commission Report</span>
          </li>
        </ol>
      </nav>

      <h1 className="mt-3 text-3xl font-bold tracking-tight text-foreground text-balance">
        Commission Report
      </h1>
      <p className="mt-3 max-w-2xl text-base leading-relaxed text-muted-foreground text-pretty">
        View your earned, received, and pending commission on mobile, with advanced filters, tabs for different insurance types, and detailed policy views.
      </p>

      <div className="mt-12 flex flex-col gap-12">
        {/* 1. Overview */}
        <DocSection id="overview" title="1. Overview">
          <p>
            The <strong className="text-foreground">Commission Report</strong> screen allows you to track and manage all commissions generated by your agency. You can filter reports, view commissions by insurance type, and drill down into individual policy details for further actions.
          </p>

          <figure className="mt-8 overflow-hidden rounded-lg border border-border bg-card">
            <div className="flex justify-center px-4 pt-4">
              <Image
                src="/financial/Screenshot_2026-07-14-15-11-23-54_22ddf5fab50861c2ddb5faf23edfa8eb.jpg"
                alt="Commission Report overview"
                width={1080}
                height={1920}
                className="w-full rounded-lg border border-border"
              />
            </div>
            <figcaption className="border-t border-border px-4 py-2.5 text-xs text-muted-foreground">
              Commission Report main screen
            </figcaption>
          </figure>
        </DocSection>

        {/* 2. All Insurance Tab */}
        <DocSection id="all-insurance" title="2. All Insurance Tab">
          <p>
            The <strong>All Insurance</strong> tab provides an aggregated view of commissions across all policies. Each card represents a policy's commission details.
          </p>
          <ul className="ml-5 mt-4 list-disc space-y-2">
            <li><strong className="text-foreground">Delete Button</strong> — Remove a specific commission record directly from the list.</li>
            <li><strong className="text-foreground">Filter Report Functionality</strong> — Open the filter menu to narrow down the report by date, agent, or company.</li>
          </ul>

          <figure className="mt-8 overflow-hidden rounded-lg border border-border bg-card">
            <div className="flex justify-center px-4 pt-4">
              <Image
                src="/financial/Screenshot_2026-07-14-15-11-41-72.jpg"
                alt="Commission Report filter"
                width={1080}
                height={1920}
                className="w-full rounded-lg border border-border"
              />
            </div>
            <figcaption className="border-t border-border px-4 py-2.5 text-xs text-muted-foreground">
              Filter report functionality on the Commission Report
            </figcaption>
          </figure>
        </DocSection>

        {/* 3. Life Insurance Commission Report */}
        <DocSection id="life-insurance" title="3. Life Insurance Commission Report">
          <p>
            Similar to the All Insurance report, the <strong>Life Insurance</strong> tab specifically filters for life policies, allowing you to track commissions exclusively for life insurance products.
          </p>
          
          <figure className="mt-8 overflow-hidden rounded-lg border border-border bg-card">
            <div className="flex justify-center px-4 pt-4">
              <Image
                src="/financial/Screenshot_2026-07-14-15-12-11-24.jpg"
                alt="Life Insurance Commission Report"
                width={1080}
                height={1920}
                className="w-full rounded-lg border border-border"
              />
            </div>
            <figcaption className="border-t border-border px-4 py-2.5 text-xs text-muted-foreground">
              Life Insurance Commission Report
            </figcaption>
          </figure>
        </DocSection>

        {/* 4. View Policy Actions */}
        <DocSection id="view-policy-actions" title="4. View Policy Actions">
          <p>
            When you click on a commission report card, it opens the full details of the insurance policy (View Policy page). From this detailed view, you have access to additional functionalities:
          </p>

          <FieldTable
            caption="View Policy Actions"
            headers={['Action', 'Description']}
            rows={[
              ['Edit Insurance', 'Modify policy details (recently added to motor insurance as well)'],
              ['Delete Insurance', 'Remove the policy from your agency book'],
              ['Add Claim Management', 'Start a claim process directly from the policy view'],
            ]}
          />

          <figure className="mt-8 overflow-hidden rounded-lg border border-border bg-card">
            <div className="flex justify-center px-4 pt-4">
              <Image
                src="/financial/Screenshot_2026-07-14-15-13-11-80.jpg"
                alt="View Policy Actions including Edit, Delete, and Add Claim Management"
                width={1080}
                height={1920}
                className="w-full rounded-lg border border-border"
              />
            </div>
            <figcaption className="border-t border-border px-4 py-2.5 text-xs text-muted-foreground">
              View Policy screen showing Edit Insurance, Delete Insurance, and Add Claim Management buttons
            </figcaption>
          </figure>
        </DocSection>

      </div>
    </DocsShell>
  )
}
